site_name: NM Förderkurs

theme:
  name: material
  language: de
  font: false
  favicon: bilder/favicon.png
  logo: bilder/logo.png

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - include-markdown
  - plantuml:
        puml_url: https://www.plantuml.com/plantuml/
        num_workers: 8

extra_css:
  - 'extra.css'

use_directory_urls: false

repo_url: https://github.com/herr-nm/MMBbS_Foerderkurs

site_url: https://herr-nm.github.io/MMBbS_Foerderkurs

nav:
    - Informationen zur Kurslizenz: 'index.md'
    - UML: 'uml.md'
    

