site_name: Förderkurs

theme:
  name: material
  language: de
  font: false
  favicon: bilder/favicon.png
  logo: bilder/logo.png

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

plugins:
  - include-markdown
  - search

extra_css:
  - 'extra.css'

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

use_directory_urls: false

repo_url: https://github.com/herr-nm/MMBbS_Foerderkurs

site_url: https://herr-nm.github.io/MMBbS_Foerderkurs

nav:
    - Informationen zur Kurslizenz: 'index.md'
    - Projekte durchführen: 'projekte_durchfuehren.md'
    - Angebot, Kaufvertrag, Mängel: 'angebot_kaufvertrag_mangel.md'
    - Informationswirtschaft: 'informationswirtschaft.md'
    - Grundlagen des Rechnungswesens: 'rechnungswesen.md'
    - Kosten- und Leistungsrechnung: 'klr.md'
    - Aufbau- und Ablauforganisation: 'aufbau_und_ablauforganisation.md'