site_name: Förderkurs

theme:
  name: material
  language: de
  font: false
  favicon: bilder/favicon.png
  logo: bilder/logo.png

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

plugins:
  - include-markdown
  - search

extra_css:
  - 'extra.css'

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

use_directory_urls: false

repo_url: https://github.com/herr-nm/MMBbS_Foerderkurs

site_url: https://herr-nm.github.io/MMBbS_Foerderkurs

nav:
    - Informationen zur Kurslizenz: 'index.md'
    - Aufbau und Inhalt der IHK-Prüfung (AP1): '00_aufbau_und_inhalt_ap1.md'
    - Aufbau und Inhalt der IHK-Prüfung (AP2): '01_aufbau_und_inhalt_ap2.md'
    - IT-Basics: '02_it_basics.md'
    - Anwendungsentwicklung: '03_anwendungsentwicklung.md'
    - IT-Sicherheit: '04_it-sicherheit.md'
    - Lernpartner, Kursangebote & Material: '08_lernpartner_kursangebote_material.md'